---
    version: "2.1"
    services:
      plex:
        image: plexinc/pms-docker
        container_name: plex
        environment:
          - PUID=1000
          - PGID=1000
          - VERSION=docker
          - PLEX_CLAIM=claim-nt5isDEucZib3Eb2zyzZ
          - TZ=America/New_York
          - ADVERTISE_IP=http://192.168.1.10:32400/
        ports:
          - 32400:32400/tcp
          - 3005:3005/tcp
          - 8324:8324/tcp
          - 32469:32469/tcp
          - 1900:1900/udp
          - 32410:32410/udp 
          - 32412:32412/udp
          - 32413:32413/udp
          - 32414:32414/udp
        hostname: 192.168.1.10
        volumes:
          - /Users/dks0499306/Projects/Home/Plex/config:/config
          - /Users/dks0499306/Projects/Home/Plex/media:/data
          - /Users/dks0499306/Projects/Home/Plex/transcode:/transcode
        restart: unless-stopped


