---
    version: "2.1"
    services:
      plex:
        image: plexinc/pms-docker
        container_name: plex
        environment:
          - PUID=1000
          - PGID=1000
          - VERSION=docker
          - PLEX_CLAIM="${PLEX_CLAIM_VALUE}"
          - TZ=America/New_York
          - ADVERTISE_IP=http://harsh-plex:32400/
        ports:
          - 32400:32400/tcp
          - 3005:3005/tcp
          - 8324:8324/tcp
          - 32469:32469/tcp
          - 1900:1900/udp
          - 32410:32410/udp 
          - 32412:32412/udp
          - 32413:32413/udp
          - 32414:32414/udp
        hostname: harsh-plex
        volumes:
          - C:\HomeLab\Plex\config:/config
          - C:\HomeLab\Plex\media:/data
          - C:\HomeLab\Plex\transcode:/transcode
        restart: unless-stopped
      jackett:
        image: ghcr.io/linuxserver/jackett
        container_name: jackett
        environment:
          - PUID=1000
          - PGID=1000
          - TZ=America/New_York
          - AUTO_UPDATE=true #optional
          #- RUN_OPTS=<run options here> #optional
        volumes:
          - C:\HomeLab\Jackett\config:/config
          - C:\HomeLab\Jackett\downloads:/downloads
        ports:
          - 9117:9117
        restart: unless-stopped

